### PR TITLE
Add Requirements file

### PR DESCRIPTION
**Pull request by cakiki**
This PR adds a requirements.txt file as per #24 

cc @osanseviero @lewtun

### CODE REVIEW

**Comment by osanseviero** [comment]
The notebook also uses 

```
translator = pipeline("translation_en_to_de", model="Helsinki-NLP/opus-mt-en-de")
```

which requires having sentencepiece installed 😄

**Comment by cakiki** [comment]
sentencepiece+protobuf are already included in the `[all]` depedencies.
Now that I think about it, `[all]` might be too beefy as it includes the following:

https://github.com/huggingface/transformers/blob/62cbd8423b3b8ab173fba9cf8c7346eca5f76d32/setup.py#L293-L304

**Comment by lewtun** [comment]
Thanks for adding this @cakiki ! I agree that the `all` dependencies are a bit beefy and take a long time to install - how about we just use

```
transformers[sentencepiece]
```

**Comment by cakiki** [comment]
Sounds good!

I'm not very familiar with pipelines; do they rely on torch? i.e. should it be `transformers[torch,sentencepiece]`?

**Comment by osanseviero** [comment]
Yes, we also need torch as a dependency! I forgot about it

**Review by osanseviero — APPROVED** [review]
Looks great! 🚀 Thanks for the PR!

**Comment by lewtun** [comment]
Ah good catch with the `torch` dependency! LGTM too - thanks!

**Pull request merged**
